name: Package
filename: package.js
web: http://github.com/markiz/jsus
description: Jsus package linked to externally replaced library 
license: Public Domain, http://unlicense.org/UNLICENSE
authors: Mark Abramov (http://github.com/markiz)
sources:
  - "Source/Library/Color.js"